export enum ValidatorType {
    VALIDATOR_TYPE_REQUIRE = 'REQUIRE',
    VALIDATOR_TYPE_MINLENGTH = 'MINLENGTH',
    VALIDATOR_TYPE_MAXLENGTH = 'MAXLENGTH',
    VALIDATOR_TYPE_EMAIL = 'EMAIL',
    VALIDATOR_TYPE_FILE = 'FILE',
    VALIDATOR_TYPE_NUMBER = 'NUMBER',
}